apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
    - image: piomin/caller-service
      jib:
        args:
          - -Pjib
          - -DskipTests
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - k8s/deployment.yaml